FROM python:3.8-alpine

# set work directory
WORKDIR /usr/src/app

COPY . .
COPY ./requirements.txt .

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# change tsinghua mirror ?
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

RUN apk add --no-cache libffi-dev py3-numpy && \
    pip3 install --upgrade pip setuptools wheel
RUN apk add --no-cache --virtual .build-deps gcc g++ jpeg-dev zlib-dev musl-dev make cmake python3-dev && \
    pip3 install matplotlib && \
    pip3 install streamlit && \
    apk del .build-deps

# streamlit hello创建一个演示页面，映射80端口以便网页访问
CMD ["streamlit","hello", "--server.port","80"] 