version: '3.3'
services:
  neo4j:
    build: 
      context: ./neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - conf_volume:/var/lib/neo4j/conf
      - data_volume:/var/lib/neo4j/data
      - import_volume:/var/lib/neo4j/import
      - log_volume:/var/lib/neo4j/logs
      - plugins_volume:/var/lib/neo4j/plugins
    # environment:
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_dbms_shell_enabled=true
      # - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
  web:
    build: 
      context: ./app
    command:
      flask run --host=0.0.0.0
    ports: 
      - 8080:5000
    environment: # => a .env file
      FLASK_APP: flaskr
      FLASK_ENV: development
      

volumes: 
  conf_volume:
  data_volume:
  import_volume:
  log_volume:
  plugins_volume:
